services:
    # Generic Declaration
    Spipu\ProcessBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests,SpipuProcessBundle.php}'
        autowire: true
        autoconfigure: true

    # Services that need the container
    Spipu\ProcessBundle\Service\ConfigReader:
        autowire: true
        arguments:
            $container: '@service_container'

    Spipu\ProcessBundle\Service\InputsFactory:
        autowire: true
        arguments:
            $container: '@service_container'

    Spipu\ProcessBundle\Service\MainParameters:
        autowire: true
        arguments:
            $container: '@service_container'

    # Steps
    Spipu\ProcessBundle\Step\:
        resource: '../../Step/*'
        tags: ['spipu.process.step']
        public: true
        autowire: true

    Spipu\ProcessBundle\Step\File\ImportFileToTable:
        tags: ['spipu.process.step']
        public: true
        autowire: true
        arguments:
            $container: '@service_container'

    Spipu\ProcessBundle\Step\File\RowReader\Action\:
        resource: '../../Step/File/RowReader/Action/*'
        tags: ['spipu.process.row-reader.action']

    Spipu\ProcessBundle\Step\File\RowReader\ActionList:
        arguments:
            - !tagged 'spipu.process.row-reader.action'

    # Role Definition
    Spipu\ProcessBundle\Service\RoleDefinition:
        tags: ['spipu.user.role']

    Spipu\ProcessBundle\Form\Options\Status:
        arguments:
            - '@Spipu\ProcessBundle\Service\Status'
        public: true