# This file is part of a Spipu Bundle
#
# (c) Laurent Minguet
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
services:
    Spipu\ProcessBundle\Service\FileManagerInterface:
        class: Spipu\ProcessBundle\Service\FileManager
        arguments:
            $folderImport: '%kernel.project_dir%/var-test/import/'
            $folderExport: '%kernel.project_dir%/var-test/export/'

    Spipu\ProcessBundle\Service\ProcessManager:
        autowire: true
        public: true
